### ISSUE TITLE
Hello, KeZhi Lu

### ISSUE THREAD

**Issue by tedster0629** [bjtu-lucas-nlp/MOE-HRS#1]
Hello, How are you?
Nice to meet you.
I have some questions to you. 
I wanna discuss more details in my discord. 
https://discord.com/users/1108068920289677464
Thanks.

**Comment by bjtu-lucas-nlp** [comment]
Hi,
I tried that link, but it's invalid. Could you please create a new one? Thanks.

**Comment by tedster0629** [comment]
https://discord.com/users/1108068920289677464
this is my discord account dm link. 
You can find me using my discord id 
tedster629. this is my discord name. 
hope to talk with you in there.
